### ISSUE TITLE
EX003 EDS - Extend delete/modify block set on Status, also on linked tables (WI 7041)

### ISSUE THREAD

**Issue by Nyryus** [EOS-Solutions/IDEAS#14]
Extend the functionality "Block delete/modify" on linked tables.
For example for Customer is should be able to block Agents, Banks, Shipment Address, ...

Ideas Owner: Agostino Martino #CAS-13050-N7T5Q5

**Comment by AndreaDiCeglie** [comment]
This cannot be implemented for generic linked table since we cannot block always OnModify and we cannot add all pages in EDS app. The idea is to add a preset list of included tables and pages that are supported.
Provide extension events and sample for additional table that can be added through customizations

**Comment by ElioCometto** [comment]
Created procedure handling the blocking of the following records:

- "Customer Bank Account"
- "Vendor Bank Account"
- "Ship-to Address"
- "Order Address"
- "Comment Line"
- "Default Dimension"

Added the above codeunit on the sample repository:

https://github.com/EOS-Solutions/Sample/blob/master/EX003.DataSecurity/01_SampleExtension/Source/Codeunit/codeunit%2018122159%20EOS003%20Blocked%20Record%20Mgt..al
