### ISSUE TITLE
CFG: Creazione variante o codice articolo pilotato da regola e non da setup generale (WI 10686)

### ISSUE THREAD

**Issue by emilianodolif** [EOS-Solutions/IDEAS#151]
Ciao,
sarebbe utile poter specificare il tipo di gestione della creazione di nuovi articoli o varianti sulla regola.
Attualmente si può scegliere un'unica opzione per tutti gli articoli, vincolando quindi la scelta.

Può capitare di dover gestire alcuni articoli con la creazione di varianti, e in contemporanea averne altri che devono essere gestiti come articoli effettivi.
Assegnando la gestione sulla regola, si avrebbe la possibilità di gestire entrambe le soluzioni.

Grazie,
Emiliano.

**Comment by MartinSchnurrKUMAVISION** [comment]
Hello,

we can only support Emiliano's suggestion, since we already have inquiries in this direction.

Our considerations, or an inquiry we have received, even goes one step further. Namely, to attach the decision to a characteristic value of a characteristic within the rule.

Please include the thought or this request in the consideration.

Many thanks.

Best Regards
Martin
