### ISSUE TITLE
Show comments on documents: Show comment pop-up as well when creating a Sales Quotation from the contact card in BC (Page 5050), via the "Create Sales Quote" button. (WI 12623)

### ISSUE THREAD

**Issue by ritchiepiessens** [EOS-Solutions/IDEAS#216]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When creating a Sales Quotation from the contact card in BC (Page 5050). Via the "Create Sales Quote" button.
We would like to show the comments (which you want to see as a pop-up) as well when you create a Sales Quotation using this method. 

**Describe alternatives you've considered**
None available

**Additional context**
![image](https://user-images.githubusercontent.com/132893818/236791899-16ec328c-7fa0-4389-bf87-b6764269732a.png)

**Comment by hemisphera** [comment]
At the moment implementing this is not so easy because there are no events that allow us to hook into the creation of the quote after the quote has been created. This would require duplicating code which we would like to avoid if possible. For now we have filed an event request at https://github.com/microsoft/ALAppExtensions/issues/24205. When I get a response, I will decide how to move forward
