### ISSUE TITLE
Translate G/L account in the prepayment

### ISSUE THREAD

**Issue by KAGlasbergen** [EOS-Solutions/IDEAS#225]
In one of the apps i have the option to translate the G/l account in the chart of account. Only when I post the prepayment the g/l account is not translated in the posted sales invoice. 
Can you change this that it will be translated?

**Comment by AndreaDiCeglie** [comment]
Translating data during posting will not be considered as an option since data should remain in internal application language (for all users not depending on client language or customer language).

We only evaluate a new capability to translate data printing the document and this will (if confirmed) implemented only in Advanced Document Reporting App.

**Comment by AndreaDiCeglie** [comment]
As best practice data that can be edited on document should not be translated at print time
