### ISSUE TITLE
Custom Report Layout per CWS

### ISSUE THREAD

**Issue by Eosjbachmann** [EOS-Solutions/IDEAS#238]
Per il CWS (Combine Warehouse Shipping), sarebbe utile se si  potesse aggiungere il Custom Report Layout (esistente nella selezione report).

![image](https://github.com/EOS-Solutions/IDEAS/assets/143101945/28e717b2-86f4-45ab-b83e-0fe7c13a4b12)

![image](https://github.com/EOS-Solutions/IDEAS/assets/143101945/aef4978f-68a2-45e6-9213-2383839664be)

**Comment by AndreaDiCeglie** [comment]
The request is not clear, please elaborate specification and use English both for request and screenshot

**Comment by Eosjbachmann** [comment]
For the CWS (Combine Warehouse Shipping), it would be useful if one could add the custom report layout (which is already available in the report selection). 

![image](https://github.com/EOS-Solutions/IDEAS/assets/143101945/5392477f-c7fb-4278-bb2e-d9970d149e71)

![image](https://github.com/EOS-Solutions/IDEAS/assets/143101945/8174d558-8a22-4e34-8298-93041a3a52bc)

**Comment by AndreaDiCeglie** [comment]
This fields, is standard field added from Microsoft to manage customer and vendor layouts.
Is not intended to be used as default to print custom layout and cannot be set from Report Selection page.
This field is available on table but not on page also for Sales and purchase report selection.

The request cannot be accepted because is changing the initial design and intention defined by MS
