### ISSUE TITLE
IPL: Estendere la gestione dei piani di fatturazione anche sugli ordini/fatture di acquisto (WI 8238)

### ISSUE THREAD

**Issue by LorenzoTrepan** [EOS-Solutions/IDEAS#24]
Estendere la funzionalità dell'app IPL dei piani di fatturazione lato passivo sugli ordini/fatture di acquisto

**Comment by matteomontanari** [comment]
This request is extremely complex and requires in-depth analysis by the relevant competence circle.
Unlike sales, we don't really control the flow in purchasing.
If we agree on a billing plan with specific dates and amounts we cannot refuse invoices transacted by the SDI just because they do not comply with the agreements. They must also be adjusted specifically with respect to standard material purchase invoices.
Scenarios that require detailed analysis.
