### ISSUE TITLE
DocSolutions for Sharepoint - Aggiunta Funzioni

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#31]
Aggiungere due funzioni Doc Solutions:

![image](https://user-images.githubusercontent.com/88732191/128988418-614427df-dd84-41ad-9d97-ae7becf92518.png)

 che restituiscano:

- nome tradotto tabella;

![image](https://user-images.githubusercontent.com/88732191/128988269-699c2251-01ae-4c8b-8bbb-76742006c935.png)

- nome tradotto tipo documento:
 
![image](https://user-images.githubusercontent.com/88732191/128988182-9dd46e89-6d05-46f3-aaf9-4fca94ff8bd7.png)

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
Adding Tables descriptions and Table names and using them on field mapping or path definition may introduce TRANSLATION ISSUES. 
Names and descriptions are depending on user settings and this may produce inconsistent storage metadata.
We suggest to use  static fixed definitions instead of dynamic descriptions
