### ISSUE TITLE
DocSolutions for Sharepoint - Aggiunta opzione upload cartelle

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#33]
Supportare, con un singolo drag and drop, l'upload di cartelle di files per allegarne l'intero contenuto.

p.s. attualmente la procedura si blocca nella fase di caricamento senza errori:

![Immagine](https://user-images.githubusercontent.com/88732191/129146683-b0e77260-30c6-4df8-b564-17d339aa9c80.png)

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
With Drag & Drop
To upload all files in a folder just open the folder click CTRL+A then drag selection to DocSolutions

With FileBox selection
Uploading an entire folder is an inconsistent design with the file selection, this may require a new user interface (new button) and this is not considered useful since selecting al files within a folder may be done just clickin CTRL+A KEY.

Additional motivation. Folder uploading need specific development for different client OS.

Uploading folders is not supported by design
