### ISSUE TITLE
OVR - DUM : Aggiunta messagio di warning anche per la Secondary Quantity

### ISSUE THREAD

**Issue by alepillon** [EOS-Solutions/IDEAS#336]
Buongiorno,

Sel i modulo OVR e' installato assieme al modulo DUM sarebbe possibile attivare il messagio di warning che segnala di aver oltrepassato la quantita' in ordine  anche sulla Secondary Quantity?

**Comment by AndreaDiCeglie** [comment]
Buongiorno,

Da un punto di vista puramente teorico è possibile avendo però un app ponte di collegamento tra le due app OVR e DUM.
By design abbiamo dichiarato che OVR supporta solo la Qta in UM 1 ossia quella primaria.

L'implementazione per supportare tutti gli scenari possibili come standard risulta piuttosto impegnativa e con qualche rischio di avere scenari non pienamente supportati.
E' probabile che su un cliente specifico con scenari e processi limitati sia più semplicemente sviluppabile il **solo warning** implementando una soluzione custom PTE con dipendenze verso entrambe le app.

Andrea
