### ISSUE TITLE
DocSolutions for FileSystem - Aggiunta opzione upload cartelle

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#34]
Supportare, con un singolo drag and drop, l'upload di cartelle di files per allegarne l'intero contenuto.

p.s. attualmente la procedura si blocca nella fase di caricamento senza errori:

![image](https://user-images.githubusercontent.com/88732191/129151550-71650a7e-b698-4db9-bae0-8438fdffd5df.png)

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
With Drag & Drop
To upload all files in a folder just open the folder click CTRL+A then drag selection to DocSolutions

With FileBox selection
Uploading an entire folder is an inconsistent design with the file selection, this may require a new user interface (new button) and this is not considered useful since selecting al files within a folder may be done just clickin CTRL+A KEY.

Additional motivation. Folder uploading need specific development for different client OS.

Uploading folders is not supported by design
