### ISSUE TITLE
EOS Packing List app. Cubage management in Packing List document (WI 7945)

### ISSUE THREAD

**Issue by JoxiSan** [EOS-Solutions/IDEAS#56]
Customer complained because Packing list document printout manages cubage information wrongly.
Packaging material definition allow product dimensions definition in mm (Length, Width and Height) and cubage in m3 is calculated automatically.
Item Unit of measure include Length, Width and Heigth fields to define dimensions (definition is normally done in mm). Cubage field is automatically calculated in mm3.

When Packing list document is printed, total cubage is calculated as Handling unit cubage + items cubage. This formula is wrong when items are placed inside the handling unit (Boxes). In this case cubage should be calculated as Packaging material cubage. Other Packaging materials (pallets) should be considered as a cubage to add to packing list.

On top of this, use of different units of measures in Packaging material definition (m3) and Item unit of measure (mm3) makes calculation also incorrect.

Solution suggested:
- Packaging material definition should specify how this item should be considered in Cubage calculation in Packing list.
- Cubage unit of measure for cubage field in item unit of measure should be specified in EOS Packing List setup.
- Cubage calculation in Packing list document should take into account the 2 previous topics to get handling unit cubage and packing list total cubage.

Issue has been detected by a customer using EOS Packing List app and resolution is urgent to ensure data in this document is correct and can be used during sales orders delivery.

**Comment by JoxiSan** [comment]
Hi Giuliano,
Our customer is asking us when this feature will be released.
I've realized status has been changed to Under Review today.
I really thank you if you can handle it urgently and give us visibility to share with our customer.
Thank you

**Comment by Giuliano-Velludo-EOS** [comment]
Hello Josè,

The changes have been accepted, they will be released in February 2022.
I'll keep you informed.

Best Regards


Da: JoxiSan ***@***.***>
Inviato: giovedì 9 dicembre 2021 10:39
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Giuliano Velludo ***@***.***>; Assign ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] EOS Packing List app. Cubage management in Packing List document (Issue #56)


Hi Giuliano,
Our customer is asking us when this feature will be released.
I've realized status has been changed to Under Review today.
I really thank you if you can handle it urgently and give us visibility to share with our customer.
Thank you

-
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F56%23issuecomment-989675602&data=04%7C01%7Cgiuliano.velludo%40eos-solutions.it%7Ccbb5fa4b3bf04f53271008d9baf7c993%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637746395675056663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RNH51vG2Q%2BJYE6elQs7SJBVVjZefud5p7nPCIFvZpmo%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVU62M5CRMXSD4USKWS6XCDUQB2MHANCNFSM5H4EIDRQ&data=04%7C01%7Cgiuliano.velludo%40eos-solutions.it%7Ccbb5fa4b3bf04f53271008d9baf7c993%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637746395675066629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yhNBsa81d7uF3uqUYEX%2BeLdmrLLrRdjnV7MzMVBFUA0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cgiuliano.velludo%40eos-solutions.it%7Ccbb5fa4b3bf04f53271008d9baf7c993%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637746395675066629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ptsLIpdxu8AHBfmeCGHOhIxrfckx4EznhSBgRCMkFQI%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cgiuliano.velludo%40eos-solutions.it%7Ccbb5fa4b3bf04f53271008d9baf7c993%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637746395675076580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FWfrDj3JXJeO9DxbZe%2FdEyYPiWK3K17dt1ZPfug7KKk%3D&reserved=0>.

**Comment by JoxiSan** [comment]
Hi Giuliano,
Very good news. I will inform our customer.
Let us know, please, when update is ready to deploy.
Thank you.
