### ISSUE TITLE
ECS Righe commento in fattura da spedizione (WI 8203)

### ISSUE THREAD

**Issue by stefanocorradinidoit** [EOS-Solutions/IDEAS#70]
In fase di estrazione fatture cumulative bisognerebbe inserire una opzione "Copia righe di testo" che consente di riportare sulla fattura eventuali righe di tipo commento inserite in spedizione di vendita registrata o spedizione cws registrata (se è attivo CWS)

**Comment by AndreaDiCeglie** [comment]
La richiesta è stata valutata in team ed in estrema sintesi quello che è possibile fare è implementare nell'app Extended Combine Shipment il flag così come presente sul Combine Shipment Standard che riporti tutte le righe descrittive sul ogni fattura.
In altre parole NON vengono riportate le righe descrittive in modo selettivo ma complessivo

**Comment by Chuucommie** [comment]
Ciao, la modifica è stata sviluppata e pubblicata su Integration, @stefanocorradinidoit se vuoi puoi già provarla

**Comment by alessandrovecchio** [comment]
Ciao @stefanocorradinidoit , hai avuto modo di provare la modifica eseguita da Ricardo? Chiedo per sapere se possiamo pubblicare l'app o se hai un'idea di quando potresti provarla.

Grazie

**Comment by stefanocorradinidoit** [comment]
Ciao,

spero di riuscire a provare la modifica entro la settimana

Scusate il ritardo ma sono preso con un paio di go live ...

Grazie


Stefano Corradini
CEO
DoIT80

Via G. Di Vittorio 23, 39100 Bolzano (BZ)
Sede operativa Via Zappiano 1/G/L, 41012 Carpi (MO)
Personal mail: ***@***.******@***.***>
M. +39 335 7169210 | P. +39 059 7163606
 www.eos-solutions.it<https://www.eos-solutions.it/>
***@***.***
 Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
 This e-mail (and attachments, if any) is confidential and access by anyone other than the addressee(s) is unauthorized. If you are not the intended recipient, any disclosure, copying, forwarding, or distribution of this e-mail is prohibited and immediate deletion should be effected.  We would appreciate your notifying the sender immediately should you become aware of any instances of such occurrence.

Da: Alessandro Vecchio ***@***.***>
Inviato: lunedì 31 gennaio 2022 10:16
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Stefano Corradini ***@***.***>; Mention ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] ECS Righe commento in fattura da spedizione (WI 8230) (Issue #70)


Ciao @stefanocorradinidoit<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstefanocorradinidoit&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h4gnBBD6ydSlRnu%2FBbac4I%2Bp11xz0q1iDTGS%2FogzbFo%3D&reserved=0> , hai avuto modo di provare la modifica eseguita da Ricardo? Chiedo per sapere se possiamo pubblicare l'app o se hai un'idea di quando potresti provarla.

Grazie

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F70%23issuecomment-1025526284&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d6I%2FBHLImMrmokHsqMyBZ6v80tK1HuH6JdCUe06qdYg%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXFJKG4FP36234HCAWNJLOLUYZHONANCNFSM5LJQ7IAQ&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Uh7WJ0e42J9CqOzXNGnFZ7g8zgzG1WWf4f3v0jwxrsk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kvCxqH5kTsEvRRgWDOjEgoZvplV4L70L%2BroxYZnhvrE%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cr68lX82btYIq1JQYtVBRtSNUcAoQdZPQ2JsazbsHg4%3D&reserved=0>.

**Comment by alessandrovecchio** [comment]
Ciao Stefano,
ci mancherebbe, sono sicuramente più prioritarie le attività dei live. Ti scrivevo solo perché anche noi siamo un po' intasati e quindi questo punto ancora non siamo riusciti a testarlo a dovere, era solo come promemoria.

Grazie e buona giornata.
AV

Da: stefanocorradinidoit ***@***.***>
Inviato: lunedì 31 gennaio 2022 18:43
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Alessandro Vecchio ***@***.***>; Assign ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] ECS Righe commento in fattura da spedizione (WI 8230) (Issue #70)

Ciao,

spero di riuscire a provare la modifica entro la settimana

Scusate il ritardo ma sono preso con un paio di go live ...

Grazie


Stefano Corradini
CEO
DoIT80

Via G. Di Vittorio 23, 39100 Bolzano (BZ)
Sede operativa Via Zappiano 1/G/L, 41012 Carpi (MO)
Personal mail: ***@***.******@***.***<mailto:***@***.******@***.***>>
M. +39 335 7169210 | P. +39 059 7163606
www.eos-solutions.it<https://www.eos-solutions.it/<http://www.eos-solutions.it%3chttps:/www.eos-solutions.it/>>
***@***.***<mailto:***@***.***>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
This e-mail (and attachments, if any) is confidential and access by anyone other than the addressee(s) is unauthorized. If you are not the intended recipient, any disclosure, copying, forwarding, or distribution of this e-mail is prohibited and immediate deletion should be effected. We would appreciate your notifying the sender immediately should you become aware of any instances of such occurrence.

Da: Alessandro Vecchio ***@***.***<mailto:***@***.***>>
Inviato: lunedì 31 gennaio 2022 10:16
A: EOS-Solutions/IDEAS ***@***.***<mailto:***@***.***>>
Cc: Stefano Corradini ***@***.***<mailto:***@***.***>>; Mention ***@***.***<mailto:***@***.***>>
Oggetto: Re: [EOS-Solutions/IDEAS] ECS Righe commento in fattura da spedizione (WI 8230) (Issue #70)


Ciao @stefanocorradinidoit<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstefanocorradinidoit&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h4gnBBD6ydSlRnu%2FBbac4I%2Bp11xz0q1iDTGS%2FogzbFo%3D&reserved=0> , hai avuto modo di provare la modifica eseguita da Ricardo? Chiedo per sapere se possiamo pubblicare l'app o se hai un'idea di quando potresti provarla.

Grazie

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F70%23issuecomment-1025526284&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d6I%2FBHLImMrmokHsqMyBZ6v80tK1HuH6JdCUe06qdYg%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXFJKG4FP36234HCAWNJLOLUYZHONANCNFSM5LJQ7IAQ&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Uh7WJ0e42J9CqOzXNGnFZ7g8zgzG1WWf4f3v0jwxrsk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kvCxqH5kTsEvRRgWDOjEgoZvplV4L70L%2BroxYZnhvrE%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cr68lX82btYIq1JQYtVBRtSNUcAoQdZPQ2JsazbsHg4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***<mailto:***@***.******@***.***>>>


-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F70%23issuecomment-1026039440&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4c73t6e00gEcwDJUTQ5NmFxsaRStwjkbMjqJppH%2FfWw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALZRTTC4UJOUW36XYW2BH7DUY3CY7ANCNFSM5LJQ7IAQ&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uRHs2bsafHKITsK7YMGhblq1N0AmwqOH0Oy47eOESRE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4tO493rPY1MqeieiTpc32EmBbqcv3%2BwkWUnmcibZbK8%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zi%2BYvsdXabjUhVBRzqQI66fene0ynBC%2FEGogQGCDb0Y%3D&reserved=0>.

**Comment by stefanocorradinidoit** [comment]
Ciao,

per favore potete inserire negli assegnatari Barbara Cigarini che esegue lei i test ?

Grazie

Stefano Corradini
CEO
DoIT80

Via G. Di Vittorio 23, 39100 Bolzano (BZ)
Sede operativa Via Zappiano 1/G/L, 41012 Carpi (MO)
Personal mail: ***@***.******@***.***>
M. +39 335 7169210 | P. +39 059 7163606
 www.eos-solutions.it<https://www.eos-solutions.it/>
***@***.***
 Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
 This e-mail (and attachments, if any) is confidential and access by anyone other than the addressee(s) is unauthorized. If you are not the intended recipient, any disclosure, copying, forwarding, or distribution of this e-mail is prohibited and immediate deletion should be effected.  We would appreciate your notifying the sender immediately should you become aware of any instances of such occurrence.

Da: Alessandro Vecchio ***@***.***>
Inviato: martedì 1 febbraio 2022 08:57
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Stefano Corradini ***@***.***>; Mention ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] ECS Righe commento in fattura da spedizione (WI 8230) (Issue #70)

Ciao Stefano,
ci mancherebbe, sono sicuramente più prioritarie le attività dei live. Ti scrivevo solo perché anche noi siamo un po' intasati e quindi questo punto ancora non siamo riusciti a testarlo a dovere, era solo come promemoria.

Grazie e buona giornata.
AV

Da: stefanocorradinidoit ***@***.***<mailto:***@***.***>>
Inviato: lunedì 31 gennaio 2022 18:43
A: EOS-Solutions/IDEAS ***@***.***<mailto:***@***.***>>
Cc: Alessandro Vecchio ***@***.***<mailto:***@***.***>>; Assign ***@***.***<mailto:***@***.***>>
Oggetto: Re: [EOS-Solutions/IDEAS] ECS Righe commento in fattura da spedizione (WI 8230) (Issue #70)

Ciao,

spero di riuscire a provare la modifica entro la settimana

Scusate il ritardo ma sono preso con un paio di go live ...

Grazie


Stefano Corradini
CEO
DoIT80

Via G. Di Vittorio 23, 39100 Bolzano (BZ)
Sede operativa Via Zappiano 1/G/L, 41012 Carpi (MO)
Personal mail: ***@***.******@***.***<mailto:***@***.******@***.***<mailto:***@***.******@***.***%3cmailto:***@***.******@***.***>>>
M. +39 335 7169210 | P. +39 059 7163606
www.eos-solutions.it<https://www.eos-solutions.it/<http://www.eos-solutions.it%3chttps:/www.eos-solutions.it/<http://www.eos-solutions.it%3chttps:/www.eos-solutions.it/%3chttp:/www.eos-solutions.it%3chttps:/www.eos-solutions.it/>>>
***@***.***<mailto:***@***.***<mailto:***@***.***%3cmailto:***@***.***>>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
This e-mail (and attachments, if any) is confidential and access by anyone other than the addressee(s) is unauthorized. If you are not the intended recipient, any disclosure, copying, forwarding, or distribution of this e-mail is prohibited and immediate deletion should be effected. We would appreciate your notifying the sender immediately should you become aware of any instances of such occurrence.

Da: Alessandro Vecchio ***@***.***<mailto:***@***.***<mailto:***@***.***%3cmailto:***@***.***>>>
Inviato: lunedì 31 gennaio 2022 10:16
A: EOS-Solutions/IDEAS ***@***.***<mailto:***@***.***<mailto:***@***.***%3cmailto:***@***.***>>>
Cc: Stefano Corradini ***@***.***<mailto:***@***.***<mailto:***@***.***%3cmailto:***@***.***>>>; Mention ***@***.***<mailto:***@***.***<mailto:***@***.***%3cmailto:***@***.***>>>
Oggetto: Re: [EOS-Solutions/IDEAS] ECS Righe commento in fattura da spedizione (WI 8230) (Issue #70)


Ciao @stefanocorradinidoit<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstefanocorradinidoit&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h4gnBBD6ydSlRnu%2FBbac4I%2Bp11xz0q1iDTGS%2FogzbFo%3D&reserved=0> , hai avuto modo di provare la modifica eseguita da Ricardo? Chiedo per sapere se possiamo pubblicare l'app o se hai un'idea di quando potresti provarla.

Grazie

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F70%23issuecomment-1025526284&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d6I%2FBHLImMrmokHsqMyBZ6v80tK1HuH6JdCUe06qdYg%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXFJKG4FP36234HCAWNJLOLUYZHONANCNFSM5LJQ7IAQ&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Uh7WJ0e42J9CqOzXNGnFZ7g8zgzG1WWf4f3v0jwxrsk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kvCxqH5kTsEvRRgWDOjEgoZvplV4L70L%2BroxYZnhvrE%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7Cd775c283d9a140b97e5508d9e49a634d%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792174014133824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cr68lX82btYIq1JQYtVBRtSNUcAoQdZPQ2JsazbsHg4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***<mailto:***@***.******@***.***<mailto:***@***.******@***.***%3cmailto:***@***.******@***.***>>>>


-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F70%23issuecomment-1026039440&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4c73t6e00gEcwDJUTQ5NmFxsaRStwjkbMjqJppH%2FfWw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALZRTTC4UJOUW36XYW2BH7DUY3CY7ANCNFSM5LJQ7IAQ&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uRHs2bsafHKITsK7YMGhblq1N0AmwqOH0Oy47eOESRE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4tO493rPY1MqeieiTpc32EmBbqcv3%2BwkWUnmcibZbK8%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Calessandro.vecchio%40eos-solutions.it%7C21ca8630866c4492349f08d9e4e1181e%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792477704432678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zi%2BYvsdXabjUhVBRzqQI66fene0ynBC%2FEGogQGCDb0Y%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***<mailto:***@***.******@***.***>>>


-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F70%23issuecomment-1026563757&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7C9f05c758fc48471fb25108d9e55886ad%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792990683990754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bK9JolKE1AIMSNGqXvlsPcaD5NkTIpmiM916kWmGc84%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXFJKG6VA3R4RHSGEXNBCRTUY6G6NANCNFSM5LJQ7IAQ&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7C9f05c758fc48471fb25108d9e55886ad%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792990683990754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iVC1ZkYbrmQn35EvwoL%2FE1n43gx%2FwdOd20a4x9Qw5O0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7C9f05c758fc48471fb25108d9e55886ad%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792990683990754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4Mauz0OmvyxJ5JvfgZ822k3i7qkeNgUZMfsDu454v9U%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstefano.corradini%40eos-solutions.it%7C9f05c758fc48471fb25108d9e55886ad%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637792990683990754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LxMkRddhmuR6H1pv0R8fzra029ewf0oFgCoATQr1w8Q%3D&reserved=0>.
